### ISSUE TITLE
Development scheme still has "Show" enabled, albeit it is no longer being selected by default

### ISSUE THREAD

**Issue by lemonkey** [orta/cocoapods-no-dev-schemes#4]
While Xcode doesn't change the target to the development pod anymore with this plugin :+1: , it still creates scheme with "Show" enabled. 

Is this intentional?

**Comment by orta** [comment]
This plugin only deletes the shared versions of the schemes, which is what triggers the change. I have no issue with the target being enabled in general

**Comment by lemonkey** [comment]
Works as designed then, thanks :+1
